# Generated by Django 4.1 on 2022-09-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='is_watched',
            new_name='watched',
        ),
    ]
